// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type HomeDocumentDataSlicesSlice = BannerSlice

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Título field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Insira o nome da página
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Logo cabeçalho field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Link da logo field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Insira o link para onde deve ir ao clicar na logo
   * - **API ID Path**: home.logo_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_link: prismic.LinkField

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, 'home', Lang>

type ProductsDocumentDataSlicesSlice = never

/**
 * Content for Produtos documents
 */
interface ProductsDocumentData {
  /**
   * Nome do produto field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Insira o nome do produto
   * - **API ID Path**: products.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Loja field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Insira o nome da loja
   * - **API ID Path**: products.store
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  store: prismic.KeyTextField

  /**
   * Preço sem desconto field in *Produtos*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Insira o preço sem desconto
   * - **API ID Path**: products.price_full
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price_full: prismic.NumberField

  /**
   * Preço com desconto field in *Produtos*
   *
   * - **Field Type**: Number
   * - **Placeholder**: preço com desconto
   * - **API ID Path**: products.price_discount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price_discount: prismic.NumberField

  /**
   * Telefone da loja ex: 6199999999 field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Insira o telefone da loja ex: 6199999999
   * - **API ID Path**: products.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField

  /**
   * Foto do produto 1 field in *Produtos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.photo_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_1: prismic.ImageField<never>

  /**
   * Foto do produto 2 field in *Produtos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.photo_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_2: prismic.ImageField<never>

  /**
   * Foto do produto 3 field in *Produtos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.photo_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_3: prismic.ImageField<never>

  /**
   * Slice Zone field in *Produtos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: products.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductsDocumentDataSlicesSlice> /**
   * Meta Description field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: products.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Produtos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: products.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Produtos document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsDocumentData>,
    'products',
    Lang
  >

export type AllDocumentTypes = HomeDocument | ProductsDocument

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceDefaultItem {
  /**
   * Imagem desktop field in *Banner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>

  /**
   * Imagem mobile field in *Banner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>

  /**
   * Vídeo background field in *Banner → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Insira um vídeo caso haja
   * - **API ID Path**: banner.items[].video_background
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_background: prismic.LinkToMediaField

  /**
   * Link do banner field in *Banner → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Insira um link caso haja
   * - **API ID Path**: banner.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<BannerSliceDefaultItem>
>

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<'banner', BannerSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProductsDocument,
      ProductsDocumentData,
      ProductsDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultItem,
      BannerSliceVariation,
      BannerSliceDefault
    }
  }
}
