// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  lista_produtos: dynamic(() => import("./ListaProdutos")),
  redes_sociais: dynamic(() => import("./RedesSociais")),
};
